// <auto-generated />
using System;
using Infraestructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infraestructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Marca", b =>
                {
                    b.Property<int>("MarcaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MarcaId"));

                    b.Property<string>("NombreMarca")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MarcaId");

                    b.ToTable("Marca");

                    b.HasData(
                        new
                        {
                            MarcaId = 1,
                            NombreMarca = "Fiat"
                        },
                        new
                        {
                            MarcaId = 2,
                            NombreMarca = "Ford"
                        },
                        new
                        {
                            MarcaId = 3,
                            NombreMarca = "BMW"
                        },
                        new
                        {
                            MarcaId = 4,
                            NombreMarca = "Peugeot"
                        },
                        new
                        {
                            MarcaId = 5,
                            NombreMarca = "Toyota"
                        },
                        new
                        {
                            MarcaId = 6,
                            NombreMarca = "Volkswagen"
                        },
                        new
                        {
                            MarcaId = 7,
                            NombreMarca = "Renault"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Modelo", b =>
                {
                    b.Property<int>("ModeloId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ModeloId"));

                    b.Property<int>("MarcaId")
                        .HasColumnType("int");

                    b.Property<string>("NombreModelo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ModeloId");

                    b.HasIndex("MarcaId");

                    b.ToTable("Modelo");

                    b.HasData(
                        new
                        {
                            ModeloId = 1,
                            MarcaId = 1,
                            NombreModelo = "Siena"
                        },
                        new
                        {
                            ModeloId = 2,
                            MarcaId = 1,
                            NombreModelo = "Uno"
                        },
                        new
                        {
                            ModeloId = 3,
                            MarcaId = 1,
                            NombreModelo = "Palio"
                        },
                        new
                        {
                            ModeloId = 4,
                            MarcaId = 2,
                            NombreModelo = "Fiesta"
                        },
                        new
                        {
                            ModeloId = 5,
                            MarcaId = 2,
                            NombreModelo = "Ranger"
                        },
                        new
                        {
                            ModeloId = 6,
                            MarcaId = 2,
                            NombreModelo = "Focus"
                        },
                        new
                        {
                            ModeloId = 7,
                            MarcaId = 3,
                            NombreModelo = "320"
                        },
                        new
                        {
                            ModeloId = 8,
                            MarcaId = 3,
                            NombreModelo = "530"
                        },
                        new
                        {
                            ModeloId = 9,
                            MarcaId = 3,
                            NombreModelo = "750"
                        },
                        new
                        {
                            ModeloId = 10,
                            MarcaId = 4,
                            NombreModelo = "208"
                        },
                        new
                        {
                            ModeloId = 11,
                            MarcaId = 4,
                            NombreModelo = "308"
                        },
                        new
                        {
                            ModeloId = 12,
                            MarcaId = 4,
                            NombreModelo = "3008"
                        },
                        new
                        {
                            ModeloId = 13,
                            MarcaId = 5,
                            NombreModelo = "Corolla"
                        },
                        new
                        {
                            ModeloId = 14,
                            MarcaId = 5,
                            NombreModelo = "Hilux"
                        },
                        new
                        {
                            ModeloId = 15,
                            MarcaId = 5,
                            NombreModelo = "Etios"
                        },
                        new
                        {
                            ModeloId = 16,
                            MarcaId = 6,
                            NombreModelo = "Amarok"
                        },
                        new
                        {
                            ModeloId = 17,
                            MarcaId = 6,
                            NombreModelo = "Taos"
                        },
                        new
                        {
                            ModeloId = 18,
                            MarcaId = 7,
                            NombreModelo = "Kangoo II"
                        },
                        new
                        {
                            ModeloId = 19,
                            MarcaId = 7,
                            NombreModelo = "Sandero"
                        },
                        new
                        {
                            ModeloId = 20,
                            MarcaId = 7,
                            NombreModelo = "Stepway"
                        });
                });

            modelBuilder.Entity("Domain.Entities.VersionVehiculo", b =>
                {
                    b.Property<int>("VersionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VersionId"));

                    b.Property<int>("ModeloId")
                        .HasColumnType("int");

                    b.Property<string>("NombreVersion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PrecioBase")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("VersionId");

                    b.HasIndex("ModeloId");

                    b.ToTable("Version");

                    b.HasData(
                        new
                        {
                            VersionId = 1,
                            ModeloId = 1,
                            NombreVersion = "1.4 Fire",
                            PrecioBase = 5200000m
                        },
                        new
                        {
                            VersionId = 2,
                            ModeloId = 1,
                            NombreVersion = "1.4 Fire Way",
                            PrecioBase = 6700000m
                        },
                        new
                        {
                            VersionId = 3,
                            ModeloId = 1,
                            NombreVersion = "1.7 ELX TD L/N",
                            PrecioBase = 3600000m
                        },
                        new
                        {
                            VersionId = 4,
                            ModeloId = 2,
                            NombreVersion = "Cargo 1.3 Fire",
                            PrecioBase = 3200000m
                        },
                        new
                        {
                            VersionId = 5,
                            ModeloId = 2,
                            NombreVersion = "Fire 1.3 3P LN",
                            PrecioBase = 4500000m
                        },
                        new
                        {
                            VersionId = 6,
                            ModeloId = 2,
                            NombreVersion = "Fire 1.3 5P LN Pack C II",
                            PrecioBase = 8500000m
                        },
                        new
                        {
                            VersionId = 7,
                            ModeloId = 3,
                            NombreVersion = "WE 1.8 Adventure",
                            PrecioBase = 6487999m
                        },
                        new
                        {
                            VersionId = 8,
                            ModeloId = 3,
                            NombreVersion = "1.4 3P ELX Active",
                            PrecioBase = 8000000m
                        },
                        new
                        {
                            VersionId = 9,
                            ModeloId = 3,
                            NombreVersion = "WE 1.7 TD Adventure X-Treme",
                            PrecioBase = 4500000m
                        },
                        new
                        {
                            VersionId = 10,
                            ModeloId = 4,
                            NombreVersion = "1.6 5P Energy",
                            PrecioBase = 12900000m
                        },
                        new
                        {
                            VersionId = 11,
                            ModeloId = 4,
                            NombreVersion = "1.4 5P Edge TDCI",
                            PrecioBase = 5000000m
                        },
                        new
                        {
                            VersionId = 12,
                            ModeloId = 4,
                            NombreVersion = "Max 1.4 4P Ambiente TDCI",
                            PrecioBase = 5200000m
                        },
                        new
                        {
                            VersionId = 13,
                            ModeloId = 5,
                            NombreVersion = "2.3 DC 4X2 L/05 XL Plus",
                            PrecioBase = 12600000m
                        },
                        new
                        {
                            VersionId = 14,
                            ModeloId = 5,
                            NombreVersion = "3.0 TDI DC 4x2 L/06 XL",
                            PrecioBase = 58500000m
                        },
                        new
                        {
                            VersionId = 15,
                            ModeloId = 5,
                            NombreVersion = "3.0 Cd Xl Plus",
                            PrecioBase = 9800000m
                        },
                        new
                        {
                            VersionId = 16,
                            ModeloId = 6,
                            NombreVersion = "2.0 Se Plus At6",
                            PrecioBase = 8933000m
                        },
                        new
                        {
                            VersionId = 17,
                            ModeloId = 6,
                            NombreVersion = "1.6 S",
                            PrecioBase = 12000000m
                        },
                        new
                        {
                            VersionId = 18,
                            ModeloId = 6,
                            NombreVersion = "2.0 Se Plus At",
                            PrecioBase = 10610000m
                        },
                        new
                        {
                            VersionId = 19,
                            ModeloId = 7,
                            NombreVersion = "2.0 320i Sedan 184cv",
                            PrecioBase = 34900000m
                        },
                        new
                        {
                            VersionId = 20,
                            ModeloId = 7,
                            NombreVersion = "2.0 320i Sedan Executive",
                            PrecioBase = 19900000m
                        },
                        new
                        {
                            VersionId = 21,
                            ModeloId = 7,
                            NombreVersion = "2.0 Sdrive 20i Sportline 192cv",
                            PrecioBase = 45000000m
                        },
                        new
                        {
                            VersionId = 22,
                            ModeloId = 8,
                            NombreVersion = "3.0 530ia Sportline Sedan",
                            PrecioBase = 82900000m
                        },
                        new
                        {
                            VersionId = 23,
                            ModeloId = 8,
                            NombreVersion = "3.0 530ia Executive 258cv",
                            PrecioBase = 17000000m
                        },
                        new
                        {
                            VersionId = 24,
                            ModeloId = 8,
                            NombreVersion = "3.0 530ia Sportline",
                            PrecioBase = 47900000m
                        },
                        new
                        {
                            VersionId = 25,
                            ModeloId = 9,
                            NombreVersion = "Serie 7 4.8 750i Premium 407cv",
                            PrecioBase = 38000000m
                        },
                        new
                        {
                            VersionId = 26,
                            ModeloId = 9,
                            NombreVersion = "Serie 7 4.8 750ia Premium Stept",
                            PrecioBase = 38000000m
                        },
                        new
                        {
                            VersionId = 27,
                            ModeloId = 9,
                            NombreVersion = "750i",
                            PrecioBase = 150000000m
                        },
                        new
                        {
                            VersionId = 28,
                            ModeloId = 10,
                            NombreVersion = "New Like",
                            PrecioBase = 20629500m
                        },
                        new
                        {
                            VersionId = 29,
                            ModeloId = 10,
                            NombreVersion = "Active Pk",
                            PrecioBase = 22987100m
                        },
                        new
                        {
                            VersionId = 30,
                            ModeloId = 10,
                            NombreVersion = "Feline AT",
                            PrecioBase = 27530600m
                        },
                        new
                        {
                            VersionId = 31,
                            ModeloId = 11,
                            NombreVersion = "2.0 Feline 143cv",
                            PrecioBase = 11000000m
                        },
                        new
                        {
                            VersionId = 32,
                            ModeloId = 11,
                            NombreVersion = "1.6 Cc Thp 156cv",
                            PrecioBase = 22000000m
                        },
                        new
                        {
                            VersionId = 33,
                            ModeloId = 11,
                            NombreVersion = "2.0 Feline 143cv Tiptronic",
                            PrecioBase = 10600000m
                        },
                        new
                        {
                            VersionId = 34,
                            ModeloId = 12,
                            NombreVersion = "GT Pack THP",
                            PrecioBase = 57592800m
                        },
                        new
                        {
                            VersionId = 35,
                            ModeloId = 13,
                            NombreVersion = "2.0 XLI CVT",
                            PrecioBase = 24447000m
                        },
                        new
                        {
                            VersionId = 36,
                            ModeloId = 13,
                            NombreVersion = "2.0 XEI CVT",
                            PrecioBase = 26468000m
                        },
                        new
                        {
                            VersionId = 37,
                            ModeloId = 13,
                            NombreVersion = "2.0 SEG CVT",
                            PrecioBase = 29625000m
                        },
                        new
                        {
                            VersionId = 38,
                            ModeloId = 14,
                            NombreVersion = "Cabina Simple DX 4x2",
                            PrecioBase = 28669000m
                        },
                        new
                        {
                            VersionId = 39,
                            ModeloId = 14,
                            NombreVersion = "Cabina Simple DX 4x4",
                            PrecioBase = 34566000m
                        },
                        new
                        {
                            VersionId = 40,
                            ModeloId = 14,
                            NombreVersion = "Cabina Doble DX 4x2",
                            PrecioBase = 32306000m
                        },
                        new
                        {
                            VersionId = 41,
                            ModeloId = 15,
                            NombreVersion = "X 6 M/T",
                            PrecioBase = 15500000m
                        },
                        new
                        {
                            VersionId = 42,
                            ModeloId = 15,
                            NombreVersion = "XLS Pack 6 M/T",
                            PrecioBase = 19500000m
                        },
                        new
                        {
                            VersionId = 43,
                            ModeloId = 15,
                            NombreVersion = "XLS Pack 4 A/T",
                            PrecioBase = 21900000m
                        },
                        new
                        {
                            VersionId = 44,
                            ModeloId = 16,
                            NombreVersion = "Trendline",
                            PrecioBase = 18900000m
                        },
                        new
                        {
                            VersionId = 45,
                            ModeloId = 16,
                            NombreVersion = "Comfortline",
                            PrecioBase = 34400000m
                        },
                        new
                        {
                            VersionId = 46,
                            ModeloId = 16,
                            NombreVersion = "Highline",
                            PrecioBase = 42300000m
                        },
                        new
                        {
                            VersionId = 47,
                            ModeloId = 17,
                            NombreVersion = "Comfortline",
                            PrecioBase = 32000000m
                        },
                        new
                        {
                            VersionId = 48,
                            ModeloId = 17,
                            NombreVersion = "Highline",
                            PrecioBase = 40060000m
                        },
                        new
                        {
                            VersionId = 49,
                            ModeloId = 17,
                            NombreVersion = "Hero",
                            PrecioBase = 39900000m
                        },
                        new
                        {
                            VersionId = 50,
                            ModeloId = 18,
                            NombreVersion = "ZEN 1.6 SCe",
                            PrecioBase = 27894900m
                        },
                        new
                        {
                            VersionId = 51,
                            ModeloId = 18,
                            NombreVersion = "STEPWAY 1.6 SCe",
                            PrecioBase = 28584120m
                        },
                        new
                        {
                            VersionId = 52,
                            ModeloId = 18,
                            NombreVersion = "STEPWAY 1.5 dCi",
                            PrecioBase = 29814964m
                        },
                        new
                        {
                            VersionId = 53,
                            ModeloId = 19,
                            NombreVersion = "Life 1.6",
                            PrecioBase = 23112016m
                        },
                        new
                        {
                            VersionId = 54,
                            ModeloId = 19,
                            NombreVersion = "Intens 1.6",
                            PrecioBase = 25036944m
                        },
                        new
                        {
                            VersionId = 55,
                            ModeloId = 19,
                            NombreVersion = "Intens 1.6 CVT",
                            PrecioBase = 25695754m
                        },
                        new
                        {
                            VersionId = 56,
                            ModeloId = 20,
                            NombreVersion = "Intens 1.6",
                            PrecioBase = 25120636m
                        },
                        new
                        {
                            VersionId = 57,
                            ModeloId = 20,
                            NombreVersion = "Intens 1.6 CVT",
                            PrecioBase = 26030524m
                        });
                });

            modelBuilder.Entity("Domain.Entitys.BienAsegurado", b =>
                {
                    b.Property<int>("BienAseguradoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BienAseguradoId"));

                    b.Property<string>("CodChasis")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CodMotor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Patente")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("TieneGnc")
                        .HasColumnType("bit");

                    b.Property<int>("UbicacionId")
                        .HasColumnType("int");

                    b.Property<bool>("UsoParticular")
                        .HasColumnType("bit");

                    b.Property<int>("VersionId")
                        .HasColumnType("int");

                    b.HasKey("BienAseguradoId");

                    b.HasIndex("UbicacionId")
                        .IsUnique();

                    b.ToTable("BienAsegurado");
                });

            modelBuilder.Entity("Domain.Entitys.Localidad", b =>
                {
                    b.Property<int>("LocalidadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocalidadId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LocalidadId");

                    b.ToTable("Localidad");

                    b.HasData(
                        new
                        {
                            LocalidadId = 1,
                            Nombre = "Morón"
                        },
                        new
                        {
                            LocalidadId = 2,
                            Nombre = "San Justo"
                        },
                        new
                        {
                            LocalidadId = 3,
                            Nombre = "San Martín"
                        },
                        new
                        {
                            LocalidadId = 4,
                            Nombre = "Quilmes"
                        },
                        new
                        {
                            LocalidadId = 5,
                            Nombre = "Lanús"
                        },
                        new
                        {
                            LocalidadId = 6,
                            Nombre = "Avellaneda"
                        },
                        new
                        {
                            LocalidadId = 7,
                            Nombre = "Vicente López"
                        },
                        new
                        {
                            LocalidadId = 8,
                            Nombre = "San Isidro"
                        },
                        new
                        {
                            LocalidadId = 9,
                            Nombre = "Tigre"
                        },
                        new
                        {
                            LocalidadId = 10,
                            Nombre = "San Fernando"
                        },
                        new
                        {
                            LocalidadId = 11,
                            Nombre = "Pilar"
                        },
                        new
                        {
                            LocalidadId = 12,
                            Nombre = "Escobar"
                        },
                        new
                        {
                            LocalidadId = 13,
                            Nombre = "Moreno"
                        },
                        new
                        {
                            LocalidadId = 14,
                            Nombre = "Lomas de Zamora"
                        },
                        new
                        {
                            LocalidadId = 15,
                            Nombre = "Adrogué"
                        },
                        new
                        {
                            LocalidadId = 16,
                            Nombre = "Banfield"
                        },
                        new
                        {
                            LocalidadId = 17,
                            Nombre = "Temperley"
                        },
                        new
                        {
                            LocalidadId = 18,
                            Nombre = "Hurlingham"
                        },
                        new
                        {
                            LocalidadId = 19,
                            Nombre = "Ituzaingó"
                        },
                        new
                        {
                            LocalidadId = 20,
                            Nombre = "Castelar"
                        },
                        new
                        {
                            LocalidadId = 21,
                            Nombre = "Ramos Mejía"
                        },
                        new
                        {
                            LocalidadId = 22,
                            Nombre = "Merlo"
                        },
                        new
                        {
                            LocalidadId = 23,
                            Nombre = "Ezeiza"
                        },
                        new
                        {
                            LocalidadId = 24,
                            Nombre = "Berazategui"
                        },
                        new
                        {
                            LocalidadId = 25,
                            Nombre = "Florencio Varela"
                        },
                        new
                        {
                            LocalidadId = 26,
                            Nombre = "General Rodríguez"
                        },
                        new
                        {
                            LocalidadId = 27,
                            Nombre = "Villa Ballester"
                        },
                        new
                        {
                            LocalidadId = 28,
                            Nombre = "Bella Vista"
                        },
                        new
                        {
                            LocalidadId = 29,
                            Nombre = "Ciudadela"
                        });
                });

            modelBuilder.Entity("Domain.Entitys.Poliza", b =>
                {
                    b.Property<int>("PolizaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PolizaId"));

                    b.Property<int>("BienAseguradoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaVencimiento")
                        .HasColumnType("datetime2");

                    b.Property<int>("NroDePoliza")
                        .HasMaxLength(9)
                        .HasColumnType("int");

                    b.Property<int>("PlanId")
                        .HasColumnType("int");

                    b.Property<decimal>("Prima")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PolizaId");

                    b.HasIndex("BienAseguradoId")
                        .IsUnique();

                    b.ToTable("Poliza");
                });

            modelBuilder.Entity("Domain.Entitys.Provincia", b =>
                {
                    b.Property<int>("ProvinciaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProvinciaId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProvinciaId");

                    b.ToTable("Provincia");

                    b.HasData(
                        new
                        {
                            ProvinciaId = 1,
                            Nombre = "Buenos Aires"
                        });
                });

            modelBuilder.Entity("Domain.Entitys.Siniestro", b =>
                {
                    b.Property<int>("SiniestroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SiniestroId"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("Imagenes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PolizaId")
                        .HasColumnType("int");

                    b.Property<bool>("TieneTercerosInvolucrados")
                        .HasColumnType("bit");

                    b.Property<int>("UbicacionId")
                        .HasColumnType("int");

                    b.HasKey("SiniestroId");

                    b.HasIndex("PolizaId");

                    b.HasIndex("UbicacionId")
                        .IsUnique();

                    b.ToTable("Siniestro");
                });

            modelBuilder.Entity("Domain.Entitys.SiniestroTipoDeSiniestro", b =>
                {
                    b.Property<int>("SiniestroId")
                        .HasColumnType("int");

                    b.Property<int>("TipoDeSiniestroId")
                        .HasColumnType("int");

                    b.HasKey("SiniestroId", "TipoDeSiniestroId");

                    b.HasIndex("TipoDeSiniestroId");

                    b.ToTable("SiniestroTipoDeSiniestro");
                });

            modelBuilder.Entity("Domain.Entitys.Tercero", b =>
                {
                    b.Property<int>("TerceroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TerceroId"));

                    b.Property<string>("CompaniaDeSeguro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Patente")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SiniestroId")
                        .HasColumnType("int");

                    b.Property<int>("Telefono")
                        .HasColumnType("int");

                    b.Property<int>("UbicacionId")
                        .HasColumnType("int");

                    b.HasKey("TerceroId");

                    b.HasIndex("SiniestroId");

                    b.HasIndex("UbicacionId")
                        .IsUnique();

                    b.ToTable("Tercero");
                });

            modelBuilder.Entity("Domain.Entitys.TipoDeSiniestro", b =>
                {
                    b.Property<int>("TipoDeSiniestroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipoDeSiniestroId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TipoDeSiniestroId");

                    b.ToTable("TipoDeSiniestro");

                    b.HasData(
                        new
                        {
                            TipoDeSiniestroId = 1,
                            Nombre = "Accidente de transito"
                        },
                        new
                        {
                            TipoDeSiniestroId = 2,
                            Nombre = "Granizo"
                        },
                        new
                        {
                            TipoDeSiniestroId = 3,
                            Nombre = "Incendio"
                        },
                        new
                        {
                            TipoDeSiniestroId = 4,
                            Nombre = "Inundación"
                        },
                        new
                        {
                            TipoDeSiniestroId = 5,
                            Nombre = "Robo"
                        },
                        new
                        {
                            TipoDeSiniestroId = 6,
                            Nombre = "Rotura"
                        });
                });

            modelBuilder.Entity("Domain.Entitys.Ubicacion", b =>
                {
                    b.Property<int>("UbicacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UbicacionId"));

                    b.Property<int>("Altura")
                        .HasColumnType("int");

                    b.Property<string>("Calle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LocalidadId")
                        .HasColumnType("int");

                    b.Property<int>("ProvinciaId")
                        .HasColumnType("int");

                    b.HasKey("UbicacionId");

                    b.ToTable("Ubicacion");
                });

            modelBuilder.Entity("Domain.Entities.Modelo", b =>
                {
                    b.HasOne("Domain.Entities.Marca", "Marca")
                        .WithMany("Modelos")
                        .HasForeignKey("MarcaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Marca");
                });

            modelBuilder.Entity("Domain.Entities.VersionVehiculo", b =>
                {
                    b.HasOne("Domain.Entities.Modelo", "Modelo")
                        .WithMany("vehiculoVersiones")
                        .HasForeignKey("ModeloId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Modelo");
                });

            modelBuilder.Entity("Domain.Entitys.BienAsegurado", b =>
                {
                    b.HasOne("Domain.Entitys.Ubicacion", "Ubicacion")
                        .WithOne("BienAsegurado")
                        .HasForeignKey("Domain.Entitys.BienAsegurado", "UbicacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ubicacion");
                });

            modelBuilder.Entity("Domain.Entitys.Poliza", b =>
                {
                    b.HasOne("Domain.Entitys.BienAsegurado", "BienAsegurado")
                        .WithOne("Poliza")
                        .HasForeignKey("Domain.Entitys.Poliza", "BienAseguradoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BienAsegurado");
                });

            modelBuilder.Entity("Domain.Entitys.Siniestro", b =>
                {
                    b.HasOne("Domain.Entitys.Poliza", "Poliza")
                        .WithMany("Siniestros")
                        .HasForeignKey("PolizaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Entitys.Ubicacion", "Ubicacion")
                        .WithOne("Siniestro")
                        .HasForeignKey("Domain.Entitys.Siniestro", "UbicacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Poliza");

                    b.Navigation("Ubicacion");
                });

            modelBuilder.Entity("Domain.Entitys.SiniestroTipoDeSiniestro", b =>
                {
                    b.HasOne("Domain.Entitys.Siniestro", "Siniestro")
                        .WithMany("SiniestroTipoDeSiniestros")
                        .HasForeignKey("SiniestroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entitys.TipoDeSiniestro", "TipoDeSiniestro")
                        .WithMany("SiniestroTipoDeSiniestros")
                        .HasForeignKey("TipoDeSiniestroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Siniestro");

                    b.Navigation("TipoDeSiniestro");
                });

            modelBuilder.Entity("Domain.Entitys.Tercero", b =>
                {
                    b.HasOne("Domain.Entitys.Siniestro", "Siniestro")
                        .WithMany("TercerosInvolucrados")
                        .HasForeignKey("SiniestroId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Entitys.Ubicacion", "Ubicacion")
                        .WithOne("Tercero")
                        .HasForeignKey("Domain.Entitys.Tercero", "UbicacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Siniestro");

                    b.Navigation("Ubicacion");
                });

            modelBuilder.Entity("Domain.Entities.Marca", b =>
                {
                    b.Navigation("Modelos");
                });

            modelBuilder.Entity("Domain.Entities.Modelo", b =>
                {
                    b.Navigation("vehiculoVersiones");
                });

            modelBuilder.Entity("Domain.Entitys.BienAsegurado", b =>
                {
                    b.Navigation("Poliza")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entitys.Poliza", b =>
                {
                    b.Navigation("Siniestros");
                });

            modelBuilder.Entity("Domain.Entitys.Siniestro", b =>
                {
                    b.Navigation("SiniestroTipoDeSiniestros");

                    b.Navigation("TercerosInvolucrados");
                });

            modelBuilder.Entity("Domain.Entitys.TipoDeSiniestro", b =>
                {
                    b.Navigation("SiniestroTipoDeSiniestros");
                });

            modelBuilder.Entity("Domain.Entitys.Ubicacion", b =>
                {
                    b.Navigation("BienAsegurado")
                        .IsRequired();

                    b.Navigation("Siniestro")
                        .IsRequired();

                    b.Navigation("Tercero")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
