// <auto-generated />
using Infraestructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infraestructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240615173054_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.AnioVehiculo", b =>
                {
                    b.Property<int>("AnioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnioId"));

                    b.Property<int>("AnioVehiculoDesde")
                        .HasColumnType("int");

                    b.Property<int>("AnioVehiculoHasta")
                        .HasColumnType("int");

                    b.Property<string>("Peso")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AnioId");

                    b.ToTable("AnioVehiculo");

                    b.HasData(
                        new
                        {
                            AnioId = 1,
                            AnioVehiculoDesde = 1,
                            AnioVehiculoHasta = 1989,
                            Peso = "0.0007"
                        },
                        new
                        {
                            AnioId = 2,
                            AnioVehiculoDesde = 1990,
                            AnioVehiculoHasta = 1999,
                            Peso = "0.0005"
                        },
                        new
                        {
                            AnioId = 3,
                            AnioVehiculoDesde = 2000,
                            AnioVehiculoHasta = 2009,
                            Peso = "0.0004"
                        },
                        new
                        {
                            AnioId = 4,
                            AnioVehiculoDesde = 2010,
                            AnioVehiculoHasta = 2019,
                            Peso = "0.0003"
                        },
                        new
                        {
                            AnioId = 5,
                            AnioVehiculoDesde = 2020,
                            AnioVehiculoHasta = 2024,
                            Peso = "0.0001"
                        });
                });

            modelBuilder.Entity("Domain.Entities.GNC", b =>
                {
                    b.Property<int>("GNCId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GNCId"));

                    b.Property<bool>("HasGNC")
                        .HasColumnType("bit");

                    b.Property<string>("Peso")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GNCId");

                    b.ToTable("GNC");

                    b.HasData(
                        new
                        {
                            GNCId = 1,
                            HasGNC = true,
                            Peso = "0.0001"
                        },
                        new
                        {
                            GNCId = 2,
                            HasGNC = false,
                            Peso = "0"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Localidad", b =>
                {
                    b.Property<int>("LocalidadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocalidadId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Peso")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LocalidadId");

                    b.ToTable("Localidad");

                    b.HasData(
                        new
                        {
                            LocalidadId = 1,
                            Nombre = "Morón",
                            Peso = "0.0005"
                        },
                        new
                        {
                            LocalidadId = 2,
                            Nombre = "San Justo",
                            Peso = "0.0006"
                        },
                        new
                        {
                            LocalidadId = 3,
                            Nombre = "San Martín",
                            Peso = "0.0004"
                        },
                        new
                        {
                            LocalidadId = 4,
                            Nombre = "Quilmes",
                            Peso = "0.0006"
                        },
                        new
                        {
                            LocalidadId = 5,
                            Nombre = "Lanús",
                            Peso = "0.0005"
                        },
                        new
                        {
                            LocalidadId = 6,
                            Nombre = "Avellaneda",
                            Peso = "0.0004"
                        },
                        new
                        {
                            LocalidadId = 7,
                            Nombre = "Vicente López",
                            Peso = "0.0003"
                        },
                        new
                        {
                            LocalidadId = 8,
                            Nombre = "San Isidro",
                            Peso = "0.0003"
                        },
                        new
                        {
                            LocalidadId = 9,
                            Nombre = "Tigre",
                            Peso = "0.0004"
                        },
                        new
                        {
                            LocalidadId = 10,
                            Nombre = "San Fernando",
                            Peso = "0.0003"
                        },
                        new
                        {
                            LocalidadId = 11,
                            Nombre = "Pilar",
                            Peso = "0.0004"
                        },
                        new
                        {
                            LocalidadId = 12,
                            Nombre = "Escobar",
                            Peso = "0.0002"
                        },
                        new
                        {
                            LocalidadId = 13,
                            Nombre = "Moreno",
                            Peso = "0.0002"
                        },
                        new
                        {
                            LocalidadId = 14,
                            Nombre = "Lomas de Zamora",
                            Peso = "0.0002"
                        },
                        new
                        {
                            LocalidadId = 15,
                            Nombre = "Adrogué",
                            Peso = "0.0003"
                        },
                        new
                        {
                            LocalidadId = 16,
                            Nombre = "Banfield",
                            Peso = "0.0003"
                        },
                        new
                        {
                            LocalidadId = 17,
                            Nombre = "Temperley",
                            Peso = "0.0002"
                        },
                        new
                        {
                            LocalidadId = 18,
                            Nombre = "Hurlingham",
                            Peso = "0.0004"
                        },
                        new
                        {
                            LocalidadId = 19,
                            Nombre = "Ituzaingó",
                            Peso = "0.0004"
                        },
                        new
                        {
                            LocalidadId = 20,
                            Nombre = "Castelar",
                            Peso = "0.0003"
                        },
                        new
                        {
                            LocalidadId = 21,
                            Nombre = "Ramos Mejía",
                            Peso = "0.0003"
                        },
                        new
                        {
                            LocalidadId = 22,
                            Nombre = "Merlo",
                            Peso = "0.0002"
                        },
                        new
                        {
                            LocalidadId = 23,
                            Nombre = "Ezeiza",
                            Peso = "0.0002"
                        },
                        new
                        {
                            LocalidadId = 24,
                            Nombre = "Berazategui",
                            Peso = "0.0003"
                        },
                        new
                        {
                            LocalidadId = 25,
                            Nombre = "Florencio Varela",
                            Peso = "0.0003"
                        },
                        new
                        {
                            LocalidadId = 26,
                            Nombre = "General Rodríguez",
                            Peso = "0.0002"
                        },
                        new
                        {
                            LocalidadId = 27,
                            Nombre = "Villa Ballester",
                            Peso = "0.0003"
                        },
                        new
                        {
                            LocalidadId = 28,
                            Nombre = "Bella Vista",
                            Peso = "0.0002"
                        },
                        new
                        {
                            LocalidadId = 29,
                            Nombre = "Ciudadela",
                            Peso = "0.0002"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Marca", b =>
                {
                    b.Property<int>("MarcaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MarcaId"));

                    b.Property<string>("NombreMarca")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MarcaId");

                    b.ToTable("Marca");

                    b.HasData(
                        new
                        {
                            MarcaId = 1,
                            NombreMarca = "Fiat"
                        },
                        new
                        {
                            MarcaId = 2,
                            NombreMarca = "Ford"
                        },
                        new
                        {
                            MarcaId = 3,
                            NombreMarca = "BMW"
                        },
                        new
                        {
                            MarcaId = 4,
                            NombreMarca = "Peugeot"
                        },
                        new
                        {
                            MarcaId = 5,
                            NombreMarca = "Toyota"
                        },
                        new
                        {
                            MarcaId = 6,
                            NombreMarca = "Volkswagen"
                        },
                        new
                        {
                            MarcaId = 7,
                            NombreMarca = "Renault"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Modelo", b =>
                {
                    b.Property<int>("ModeloId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ModeloId"));

                    b.Property<int>("MarcaId")
                        .HasColumnType("int");

                    b.Property<string>("NombreModelo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ModeloId");

                    b.HasIndex("MarcaId");

                    b.ToTable("Modelo");

                    b.HasData(
                        new
                        {
                            ModeloId = 1,
                            MarcaId = 1,
                            NombreModelo = "Siena"
                        },
                        new
                        {
                            ModeloId = 2,
                            MarcaId = 1,
                            NombreModelo = "Uno"
                        },
                        new
                        {
                            ModeloId = 3,
                            MarcaId = 1,
                            NombreModelo = "Palio"
                        },
                        new
                        {
                            ModeloId = 4,
                            MarcaId = 2,
                            NombreModelo = "Fiesta"
                        },
                        new
                        {
                            ModeloId = 5,
                            MarcaId = 2,
                            NombreModelo = "Ranger"
                        },
                        new
                        {
                            ModeloId = 6,
                            MarcaId = 2,
                            NombreModelo = "Focus"
                        },
                        new
                        {
                            ModeloId = 7,
                            MarcaId = 3,
                            NombreModelo = "320"
                        },
                        new
                        {
                            ModeloId = 8,
                            MarcaId = 3,
                            NombreModelo = "530"
                        },
                        new
                        {
                            ModeloId = 9,
                            MarcaId = 3,
                            NombreModelo = "750"
                        },
                        new
                        {
                            ModeloId = 10,
                            MarcaId = 4,
                            NombreModelo = "208"
                        },
                        new
                        {
                            ModeloId = 11,
                            MarcaId = 4,
                            NombreModelo = "308"
                        },
                        new
                        {
                            ModeloId = 12,
                            MarcaId = 4,
                            NombreModelo = "3008"
                        },
                        new
                        {
                            ModeloId = 13,
                            MarcaId = 5,
                            NombreModelo = "Corolla"
                        },
                        new
                        {
                            ModeloId = 14,
                            MarcaId = 5,
                            NombreModelo = "Hilux"
                        },
                        new
                        {
                            ModeloId = 15,
                            MarcaId = 5,
                            NombreModelo = "Etios"
                        },
                        new
                        {
                            ModeloId = 16,
                            MarcaId = 6,
                            NombreModelo = "Amarok"
                        },
                        new
                        {
                            ModeloId = 17,
                            MarcaId = 6,
                            NombreModelo = "Taos"
                        },
                        new
                        {
                            ModeloId = 18,
                            MarcaId = 7,
                            NombreModelo = "Kangoo II"
                        },
                        new
                        {
                            ModeloId = 19,
                            MarcaId = 7,
                            NombreModelo = "Sandero"
                        },
                        new
                        {
                            ModeloId = 20,
                            MarcaId = 7,
                            NombreModelo = "Stepway"
                        });
                });

            modelBuilder.Entity("Domain.Entities.RangoEtario", b =>
                {
                    b.Property<int>("EdadRangoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EdadRangoId"));

                    b.Property<int>("EdadDesde")
                        .HasColumnType("int");

                    b.Property<int>("EdadHasta")
                        .HasColumnType("int");

                    b.Property<string>("Peso")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EdadRangoId");

                    b.ToTable("RangoEtario");

                    b.HasData(
                        new
                        {
                            EdadRangoId = 1,
                            EdadDesde = 18,
                            EdadHasta = 40,
                            Peso = "0.0005"
                        },
                        new
                        {
                            EdadRangoId = 2,
                            EdadDesde = 41,
                            EdadHasta = 60,
                            Peso = "0.0006"
                        },
                        new
                        {
                            EdadRangoId = 3,
                            EdadDesde = 61,
                            EdadHasta = 90,
                            Peso = "0.0008"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Vehiculo", b =>
                {
                    b.Property<int>("VehiculoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehiculoId"));

                    b.Property<int>("AnioVehiculo")
                        .HasColumnType("int");

                    b.Property<int>("MarcaId")
                        .HasColumnType("int");

                    b.Property<int>("ModeloId")
                        .HasColumnType("int");

                    b.Property<int>("VersionId")
                        .HasColumnType("int");

                    b.HasKey("VehiculoId");

                    b.HasIndex("MarcaId");

                    b.HasIndex("ModeloId");

                    b.HasIndex("VersionId");

                    b.ToTable("Vehiculo");
                });

            modelBuilder.Entity("Domain.Entities.VersionVehiculo", b =>
                {
                    b.Property<int>("VersionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VersionId"));

                    b.Property<int>("ModeloId")
                        .HasColumnType("int");

                    b.Property<string>("NombreVersion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PrecioBase")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("VersionId");

                    b.HasIndex("ModeloId");

                    b.ToTable("Version");

                    b.HasData(
                        new
                        {
                            VersionId = 1,
                            ModeloId = 1,
                            NombreVersion = "1.4 Fire",
                            PrecioBase = 5200000m
                        },
                        new
                        {
                            VersionId = 2,
                            ModeloId = 1,
                            NombreVersion = "1.4 Fire Way",
                            PrecioBase = 6700000m
                        },
                        new
                        {
                            VersionId = 3,
                            ModeloId = 1,
                            NombreVersion = "1.7 ELX TD L/N",
                            PrecioBase = 3600000m
                        },
                        new
                        {
                            VersionId = 4,
                            ModeloId = 2,
                            NombreVersion = "Cargo 1.3 Fire",
                            PrecioBase = 3200000m
                        },
                        new
                        {
                            VersionId = 5,
                            ModeloId = 2,
                            NombreVersion = "Fire 1.3 3P LN",
                            PrecioBase = 4500000m
                        },
                        new
                        {
                            VersionId = 6,
                            ModeloId = 2,
                            NombreVersion = "Fire 1.3 5P LN Pack C II",
                            PrecioBase = 8500000m
                        },
                        new
                        {
                            VersionId = 7,
                            ModeloId = 3,
                            NombreVersion = "WE 1.8 Adventure",
                            PrecioBase = 6487999m
                        },
                        new
                        {
                            VersionId = 8,
                            ModeloId = 3,
                            NombreVersion = "1.4 3P ELX Active",
                            PrecioBase = 8000000m
                        },
                        new
                        {
                            VersionId = 9,
                            ModeloId = 3,
                            NombreVersion = "WE 1.7 TD Adventure X-Treme",
                            PrecioBase = 4500000m
                        },
                        new
                        {
                            VersionId = 10,
                            ModeloId = 4,
                            NombreVersion = "1.6 5P Energy",
                            PrecioBase = 12900000m
                        },
                        new
                        {
                            VersionId = 11,
                            ModeloId = 4,
                            NombreVersion = "1.4 5P Edge TDCI",
                            PrecioBase = 5000000m
                        },
                        new
                        {
                            VersionId = 12,
                            ModeloId = 4,
                            NombreVersion = "Max 1.4 4P Ambiente TDCI",
                            PrecioBase = 5200000m
                        },
                        new
                        {
                            VersionId = 13,
                            ModeloId = 5,
                            NombreVersion = "2.3 DC 4X2 L/05 XL Plus",
                            PrecioBase = 12600000m
                        },
                        new
                        {
                            VersionId = 14,
                            ModeloId = 5,
                            NombreVersion = "3.0 TDI DC 4x2 L/06 XL",
                            PrecioBase = 58500000m
                        },
                        new
                        {
                            VersionId = 15,
                            ModeloId = 5,
                            NombreVersion = "3.0 Cd Xl Plus",
                            PrecioBase = 9800000m
                        },
                        new
                        {
                            VersionId = 16,
                            ModeloId = 6,
                            NombreVersion = "2.0 Se Plus At6",
                            PrecioBase = 8933000m
                        },
                        new
                        {
                            VersionId = 17,
                            ModeloId = 6,
                            NombreVersion = "1.6 S",
                            PrecioBase = 12000000m
                        },
                        new
                        {
                            VersionId = 18,
                            ModeloId = 6,
                            NombreVersion = "2.0 Se Plus At",
                            PrecioBase = 10610000m
                        },
                        new
                        {
                            VersionId = 19,
                            ModeloId = 7,
                            NombreVersion = "2.0 320i Sedan 184cv",
                            PrecioBase = 34900000m
                        },
                        new
                        {
                            VersionId = 20,
                            ModeloId = 7,
                            NombreVersion = "2.0 320i Sedan Executive",
                            PrecioBase = 19900000m
                        },
                        new
                        {
                            VersionId = 21,
                            ModeloId = 7,
                            NombreVersion = "2.0 Sdrive 20i Sportline 192cv",
                            PrecioBase = 45000000m
                        },
                        new
                        {
                            VersionId = 22,
                            ModeloId = 8,
                            NombreVersion = "3.0 530ia Sportline Sedan",
                            PrecioBase = 82900000m
                        },
                        new
                        {
                            VersionId = 23,
                            ModeloId = 8,
                            NombreVersion = "3.0 530ia Executive 258cv",
                            PrecioBase = 17000000m
                        },
                        new
                        {
                            VersionId = 24,
                            ModeloId = 8,
                            NombreVersion = "3.0 530ia Sportline",
                            PrecioBase = 47900000m
                        },
                        new
                        {
                            VersionId = 25,
                            ModeloId = 9,
                            NombreVersion = "Serie 7 4.8 750i Premium 407cv",
                            PrecioBase = 38000000m
                        },
                        new
                        {
                            VersionId = 26,
                            ModeloId = 9,
                            NombreVersion = "Serie 7 4.8 750ia Premium Stept",
                            PrecioBase = 38000000m
                        },
                        new
                        {
                            VersionId = 27,
                            ModeloId = 9,
                            NombreVersion = "750i",
                            PrecioBase = 150000000m
                        },
                        new
                        {
                            VersionId = 28,
                            ModeloId = 10,
                            NombreVersion = "New Like",
                            PrecioBase = 20629500m
                        },
                        new
                        {
                            VersionId = 29,
                            ModeloId = 10,
                            NombreVersion = "Active Pk",
                            PrecioBase = 22987100m
                        },
                        new
                        {
                            VersionId = 30,
                            ModeloId = 10,
                            NombreVersion = "Feline AT",
                            PrecioBase = 27530600m
                        },
                        new
                        {
                            VersionId = 31,
                            ModeloId = 11,
                            NombreVersion = "2.0 Feline 143cv",
                            PrecioBase = 11000000m
                        },
                        new
                        {
                            VersionId = 32,
                            ModeloId = 11,
                            NombreVersion = "1.6 Cc Thp 156cv",
                            PrecioBase = 22000000m
                        },
                        new
                        {
                            VersionId = 33,
                            ModeloId = 11,
                            NombreVersion = "2.0 Feline 143cv Tiptronic",
                            PrecioBase = 10600000m
                        },
                        new
                        {
                            VersionId = 34,
                            ModeloId = 12,
                            NombreVersion = "GT Pack THP",
                            PrecioBase = 57592800m
                        },
                        new
                        {
                            VersionId = 35,
                            ModeloId = 13,
                            NombreVersion = "2.0 XLI CVT",
                            PrecioBase = 24447000m
                        },
                        new
                        {
                            VersionId = 36,
                            ModeloId = 13,
                            NombreVersion = "2.0 XEI CVT",
                            PrecioBase = 26468000m
                        },
                        new
                        {
                            VersionId = 37,
                            ModeloId = 13,
                            NombreVersion = "2.0 SEG CVT",
                            PrecioBase = 29625000m
                        },
                        new
                        {
                            VersionId = 38,
                            ModeloId = 14,
                            NombreVersion = "Cabina Simple DX 4x2",
                            PrecioBase = 28669000m
                        },
                        new
                        {
                            VersionId = 39,
                            ModeloId = 14,
                            NombreVersion = "Cabina Simple DX 4x4",
                            PrecioBase = 34566000m
                        },
                        new
                        {
                            VersionId = 40,
                            ModeloId = 14,
                            NombreVersion = "Cabina Doble DX 4x2",
                            PrecioBase = 32306000m
                        },
                        new
                        {
                            VersionId = 41,
                            ModeloId = 15,
                            NombreVersion = "X 6 M/T",
                            PrecioBase = 15500000m
                        },
                        new
                        {
                            VersionId = 42,
                            ModeloId = 15,
                            NombreVersion = "XLS Pack 6 M/T",
                            PrecioBase = 19500000m
                        },
                        new
                        {
                            VersionId = 43,
                            ModeloId = 15,
                            NombreVersion = "XLS Pack 4 A/T",
                            PrecioBase = 21900000m
                        },
                        new
                        {
                            VersionId = 44,
                            ModeloId = 16,
                            NombreVersion = "Trendline",
                            PrecioBase = 18900000m
                        },
                        new
                        {
                            VersionId = 45,
                            ModeloId = 16,
                            NombreVersion = "Comfortline",
                            PrecioBase = 34400000m
                        },
                        new
                        {
                            VersionId = 46,
                            ModeloId = 16,
                            NombreVersion = "Highline",
                            PrecioBase = 42300000m
                        },
                        new
                        {
                            VersionId = 47,
                            ModeloId = 17,
                            NombreVersion = "Comfortline",
                            PrecioBase = 32000000m
                        },
                        new
                        {
                            VersionId = 48,
                            ModeloId = 17,
                            NombreVersion = "Highline",
                            PrecioBase = 40060000m
                        },
                        new
                        {
                            VersionId = 49,
                            ModeloId = 17,
                            NombreVersion = "Hero",
                            PrecioBase = 39900000m
                        },
                        new
                        {
                            VersionId = 50,
                            ModeloId = 18,
                            NombreVersion = "ZEN 1.6 SCe",
                            PrecioBase = 27894900m
                        },
                        new
                        {
                            VersionId = 51,
                            ModeloId = 18,
                            NombreVersion = "STEPWAY 1.6 SCe",
                            PrecioBase = 28584120m
                        },
                        new
                        {
                            VersionId = 52,
                            ModeloId = 18,
                            NombreVersion = "STEPWAY 1.5 dCi",
                            PrecioBase = 29814964m
                        },
                        new
                        {
                            VersionId = 53,
                            ModeloId = 19,
                            NombreVersion = "Life 1.6",
                            PrecioBase = 23112016m
                        },
                        new
                        {
                            VersionId = 54,
                            ModeloId = 19,
                            NombreVersion = "Intens 1.6",
                            PrecioBase = 25036944m
                        },
                        new
                        {
                            VersionId = 55,
                            ModeloId = 19,
                            NombreVersion = "Intens 1.6 CVT",
                            PrecioBase = 25695754m
                        },
                        new
                        {
                            VersionId = 56,
                            ModeloId = 20,
                            NombreVersion = "Intens 1.6",
                            PrecioBase = 25120636m
                        },
                        new
                        {
                            VersionId = 57,
                            ModeloId = 20,
                            NombreVersion = "Intens 1.6 CVT",
                            PrecioBase = 26030524m
                        });
                });

            modelBuilder.Entity("Domain.Entities.Modelo", b =>
                {
                    b.HasOne("Domain.Entities.Marca", "Marca")
                        .WithMany("Modelos")
                        .HasForeignKey("MarcaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Marca");
                });

            modelBuilder.Entity("Domain.Entities.Vehiculo", b =>
                {
                    b.HasOne("Domain.Entities.Marca", "Marca")
                        .WithMany("Vehiculos")
                        .HasForeignKey("MarcaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Modelo", "Modelo")
                        .WithMany("Vehiculos")
                        .HasForeignKey("ModeloId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.VersionVehiculo", "VersionVehiculo")
                        .WithMany("Vehiculos")
                        .HasForeignKey("VersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Marca");

                    b.Navigation("Modelo");

                    b.Navigation("VersionVehiculo");
                });

            modelBuilder.Entity("Domain.Entities.VersionVehiculo", b =>
                {
                    b.HasOne("Domain.Entities.Modelo", "Modelo")
                        .WithMany("vehiculoVersiones")
                        .HasForeignKey("ModeloId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Modelo");
                });

            modelBuilder.Entity("Domain.Entities.Marca", b =>
                {
                    b.Navigation("Modelos");

                    b.Navigation("Vehiculos");
                });

            modelBuilder.Entity("Domain.Entities.Modelo", b =>
                {
                    b.Navigation("Vehiculos");

                    b.Navigation("vehiculoVersiones");
                });

            modelBuilder.Entity("Domain.Entities.VersionVehiculo", b =>
                {
                    b.Navigation("Vehiculos");
                });
#pragma warning restore 612, 618
        }
    }
}
